### PR TITLE
Create sv_se.json

### PR DESCRIPTION
**Pull request by Regnander**

### CODE REVIEW

**Comment by Theta-Dev** [comment]
Nice job. I'll include your translation in the next mod version (2.5).
I have just added ingame documentation with JEI information recipes (#45). Could you translate these texts, too?

https://github.com/Theta-Dev/ConstructionWand/blob/0822539314d6075690bd0bedb5a690adbecab275/src/main/resources/assets/constructionwand/lang/en_us.json#L60-L67

**Comment by Theta-Dev** [comment]
The addition of a swapper core is a requested feature (#42). I wont have time to finish this with the next update, but when I will work on this, I would need translations for this feature too.

It would be nice if you can put these translations in a comment. I will include them when I implement this feature.

- [Item name] Swapper Wand Core
- [Option name] Swapper Core
- [Tooltip info] Swap blocks in the world with the ones in your inventory
- [JEI info] The swapper core can swap blocks in the world with blocks from your inventory. Put the desired blocks in your offhand, right click some blocks in the world and watch them change places.

**Comment by Regnander** [comment]
Alright, I can do that. I'm currently translating the strings you posted earlier as I'm writing this.

**Comment by Theta-Dev** [comment]
Thank you very much.

**Comment by Regnander** [comment]
Thank YOU for creating this mod. 😉

* [Item name] Växlingsstavskärna
* [Option name] Växlingskärna
* [Tooltip info] Byt ut block i världen med de som finns i ditt förråd
* [JEI info] Växlingskärnan kan byta ut block i världen med block från ditt förråd. Lägg de önskade blocken i din sekundära hand, högerklicka på några block i världen och se de byta plats.

**Comment by aelfwyne** [comment]
> The addition of a swapper core is a requested feature (#42). I wont have time to finish this with the next update, but when I will work on this, I would need translations for this feature too.
> 
> It would be nice if you can put these translations in a comment. I will include them when I implement this feature.
> 
> * [Item name] Swapper Wand Core
> * [Option name] Swapper Core
> * [Tooltip info] Swap blocks in the world with the ones in your inventory
> * [JEI info] The swapper core can swap blocks in the world with blocks from your inventory. Put the desired blocks in your offhand, right click some blocks in the world and watch them change places.

Hi, I see you closed the linked issue and this issue, but seemed to imply here a swapper core was coming. Did this feature request get dropped instead? Lack of a swapper core is a real bummer.

**Pull request merged**
